### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by sabetech** [virag-ky/Leaderboard#5]
The project looks great and amazing visually and the theme fits the context of the application.
Here is a list of issues to be looked at.

- I realized when I post a game score, the list is not updated with the refresh button
- The score fields can make use type="number" instead of type="text" to prevent non-numeric values from getting into the submission

**Comment by virag-ky** [comment]
Thank you @sabetech for your recommendations and for your time :+1:
